-- Script para crear tablas SIM_FT_* manualmente
-- Fecha: 2025-10-22

USE SIM_PANAMA;
GO

-- SIM_FT_ESTATUS: Catálogo de estados
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_ESTATUS')
BEGIN
    CREATE TABLE SIM_FT_ESTATUS (
        COD_ESTATUS VARCHAR(2) NOT NULL PRIMARY KEY,
        NOM_ESTATUS VARCHAR(100) NOT NULL,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME
    );
    PRINT 'Tabla SIM_FT_ESTATUS creada';
END
GO

-- SIM_FT_CONCLUSION: Tipos de conclusión
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_CONCLUSION')
BEGIN
    CREATE TABLE SIM_FT_CONCLUSION (
        COD_CONCLUSION VARCHAR(2) NOT NULL PRIMARY KEY,
        NOM_CONCLUSION VARCHAR(100) NOT NULL,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME
    );
    PRINT 'Tabla SIM_FT_CONCLUSION creada';
END
GO

-- SIM_FT_PRIORIDAD: Niveles de prioridad
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_PRIORIDAD')
BEGIN
    CREATE TABLE SIM_FT_PRIORIDAD (
        COD_PRIORIDAD VARCHAR(1) NOT NULL PRIMARY KEY,
        NOM_PRIORIDAD VARCHAR(50) NOT NULL,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME
    );
    PRINT 'Tabla SIM_FT_PRIORIDAD creada';
END
GO

-- SIM_FT_PASOS: Define los pasos genéricos
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_PASOS')
BEGIN
    CREATE TABLE SIM_FT_PASOS (
        COD_TRAMITE VARCHAR(10) NOT NULL,
        NUM_PASO INT NOT NULL,
        NOM_DESCRIPCION VARCHAR(255) NOT NULL,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME,
        PRIMARY KEY (COD_TRAMITE, NUM_PASO)
    );
    PRINT 'Tabla SIM_FT_PASOS creada';
END
GO

-- SIM_FT_PASOXTRAM: Configuración de flujo
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_PASOXTRAM')
BEGIN
    CREATE TABLE SIM_FT_PASOXTRAM (
        COD_TRAMITE VARCHAR(10) NOT NULL,
        NUM_PASO INT NOT NULL,
        COD_SECCION VARCHAR(4) NOT NULL,
        ID_PASO_SGTE INT,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME,
        PRIMARY KEY (COD_TRAMITE, NUM_PASO)
    );
    PRINT 'Tabla SIM_FT_PASOXTRAM creada';
END
GO

-- SIM_FT_USUA_SEC: Usuarios por sección
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_USUA_SEC')
BEGIN
    CREATE TABLE SIM_FT_USUA_SEC (
        ID_USUARIO VARCHAR(17) NOT NULL,
        COD_SECCION VARCHAR(4) NOT NULL,
        COD_AGENCIA VARCHAR(4) NOT NULL,
        IND_ACTIVO VARCHAR(1) NOT NULL DEFAULT 'S',
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        ID_USUARIO_MODIF VARCHAR(17),
        FEC_MODIF_REG DATETIME,
        PRIMARY KEY (ID_USUARIO, COD_SECCION, COD_AGENCIA)
    );
    PRINT 'Tabla SIM_FT_USUA_SEC creada';
END
GO

-- SIM_FT_TRAMITE_E: Encabezado del trámite
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_TRAMITE_E')
BEGIN
    CREATE TABLE SIM_FT_TRAMITE_E (
        NUM_ANNIO INT NOT NULL,
        NUM_TRAMITE INT NOT NULL,
        NUM_REGISTRO INT NOT NULL,
        COD_TRAMITE VARCHAR(10) NOT NULL,
        FEC_INI_TRAMITE DATETIME,
        FEC_FIN_TRAMITE DATETIME,
        IND_ESTATUS VARCHAR(2),
        IND_CONCLUSION VARCHAR(2),
        IND_PRIORIDAD VARCHAR(1),
        OBS_OBSERVA TEXT,
        HITS_TRAMITE INT,
        ID_USUARIO_CREA VARCHAR(17),
        FEC_ACTUALIZA DATETIME,
        PRIMARY KEY (NUM_ANNIO, NUM_TRAMITE, NUM_REGISTRO)
    );
    PRINT 'Tabla SIM_FT_TRAMITE_E creada';
END
GO

-- SIM_FT_TRAMITE_D: Detalle de pasos
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_TRAMITE_D')
BEGIN
    CREATE TABLE SIM_FT_TRAMITE_D (
        NUM_ANNIO INT NOT NULL,
        NUM_TRAMITE INT NOT NULL,
        NUM_PASO INT NOT NULL,
        NUM_REGISTRO INT NOT NULL,
        COD_TRAMITE VARCHAR(10) NOT NULL,
        NUM_ACTIVIDAD INT,
        COD_SECCION VARCHAR(4),
        COD_AGENCIA VARCHAR(4),
        ID_USUAR_RESP VARCHAR(17),
        OBS_OBSERVACION TEXT,
        NUM_PASO_SGTE INT,
        IND_ESTATUS VARCHAR(2),
        IND_CONCLUSION VARCHAR(2),
        ID_USUARIO_CREA VARCHAR(17),
        FEC_ACTUALIZA DATETIME,
        PRIMARY KEY (NUM_ANNIO, NUM_TRAMITE, NUM_PASO, NUM_REGISTRO)
    );
    PRINT 'Tabla SIM_FT_TRAMITE_D creada';
END
GO

-- SIM_FT_TRAMITE_CIERRE: Cierre de trámite
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_TRAMITE_CIERRE')
BEGIN
    CREATE TABLE SIM_FT_TRAMITE_CIERRE (
        NUM_ANNIO INT NOT NULL,
        NUM_TRAMITE INT NOT NULL,
        NUM_REGISTRO INT NOT NULL,
        FEC_CIERRE DATETIME NOT NULL,
        ID_USUARIO_CIERRE VARCHAR(17) NOT NULL,
        OBS_CIERRE TEXT,
        COD_CONCLUSION VARCHAR(2),
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        PRIMARY KEY (NUM_ANNIO, NUM_TRAMITE, NUM_REGISTRO)
    );
    PRINT 'Tabla SIM_FT_TRAMITE_CIERRE creada';
END
GO

-- SIM_FT_DEPENDTE_CIERRE: Dependientes en cierre
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SIM_FT_DEPENDTE_CIERRE')
BEGIN
    CREATE TABLE SIM_FT_DEPENDTE_CIERRE (
        NUM_ANNIO INT NOT NULL,
        NUM_TRAMITE INT NOT NULL,
        NUM_REGISTRO INT NOT NULL,
        NUM_REGISTRO_DEP INT NOT NULL,
        TIP_DEPENDENCIA VARCHAR(2),
        FEC_INCLUSION DATETIME,
        ID_USUARIO_CREA VARCHAR(17),
        FEC_CREA_REG DATETIME DEFAULT GETDATE(),
        PRIMARY KEY (NUM_ANNIO, NUM_TRAMITE, NUM_REGISTRO, NUM_REGISTRO_DEP)
    );
    PRINT 'Tabla SIM_FT_DEPENDTE_CIERRE creada';
END
GO

PRINT '=== Creación de tablas SIM_FT_* completada ==='
GO
