apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tramites-staging

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets/secrets-template.yaml
  - sqlserver
  - redis
  - backend
  - celery
  - frontend

labels:
  - pairs:
      app.kubernetes.io/name: tramites
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
